In [1]:
%matplotlib inline

import h5py
from matplotlib import pyplot as plt
import pandas as pd

In [ ]:
from io import StringIO

d = '''paste_data_here'''

pd.read_csv(StringIO(d), sep='\s+')

### Pre-filled example

In [2]:
from io import StringIO

d = '''91	866	634	613	742	585
412	937	654	651	613	761
510	536	728	826	766	967
546	155	905	424	734	894
853	683	869	32	45	63
271	568	456	811	165	945
827	354	883	445	344	242
738	302	695	0	237	175
840	307	158	183	779	847
707	767	547	261	625	903
570	7	142	810	182	195
674	192	132	409	251	319'''

pd.read_csv(StringIO(d), sep='\s+')

     91  866  634  613  742  585
0   412  937  654  651  613  761
1   510  536  728  826  766  967
2   546  155  905  424  734  894
3   853  683  869   32   45   63
4   271  568  456  811  165  945
5   827  354  883  445  344  242
6   738  302  695    0  237  175
7   840  307  158  183  779  847
8   707  767  547  261  625  903
9   570    7  142  810  182  195
10  674  192  132  409  251  319